#pragma once

namespace Editor
{
	enum class LEVEL { STATIC, EDIT, SHADER, ANIMATION, EFFECT, MAP, UI, CAMERA, STATEMACHINE, SFX, END };
	enum class CHANNEL { BGM, PLAYER_ACTION, PLAYER_VOICE, PLAYER_QTE, ENEMY_ACTION, ENEMY_VOICE, EFFECT, END };

	enum class SHADER_ANIMPATH { DEFAULT_NORMAL, NORMAL_TEXTURE, SHADOW, END };

	enum class COLLISIONLAYER { NONE, PLAYER, CHARACTER, CAMERA, PARKOUR, DETECT, GRAB, MAP, END };
	//enum class OBJECTTYPE { DEFAULT, SONORA, INTERACTION, SPAWNOR, DESTRUCTION, NONRIGID, TRIGGERBOX, NONSONORA, NONSONORA_FLOOR, METEO, WATER, COLLAPS, THROW, BURN,DOME,TURN, END };
	enum class OBJECTTYPE { DEFAULT, PARKOUR, END };
	enum class INSTANCETYPE { DEFAULT, SONORO, NONSONORO, END };
	enum class WEAPONTYPE { NONANIM, ANIM, END };

	/*
	* VAULT : 넘을 수 있는지
	* CLIMBABLE : 벽을 탈 수 있는지 (높아서?)
	* MANTLEABLE : 벽을 매달릴 수 있는지?
	*/
	enum class PARKOUR_FLAG {
		VAULTABLE	= 1 << 0, // 1
		CLIMBABLE	= 1 << 1, // 2
		HANGABLE	= 1 << 2, // 4
		MANTLEABLE	= 1 << 3, // 8 => 매달려 있는 상태에서 전환동작
		ALL = 0xF, // 15
		END
	};
}