#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOGO, GAMEPLAY, HEAVEN, LOADING, TEST, TEST_UI, END };
	enum class COLLISIONLAYER { NONE, MAP, PLAYER, INTERACTION, GRAB, DETECT, SLIDE, END };
	enum class OBJECTTYPE { DEFAULT, INTERACTION, TRIGGERBOX, TURN, END };
}