#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOGO, GAMEPLAY, HEAVEN, LOADING, TEST, TEST_UI, END };
	enum class COLLISIONLAYER { NONE, MAP, PLAYER, PARKOUR, GRAB, DETECT, SLIDE, BURN,  END };
	//enum class OBJECTTYPE { DEFAULT, SONORA, INTERACTION, SPAWNOR, DESTRUCTION, NONRIGID, TRIGGERBOX, NONSONORA, NONSONORA_FLOOR, METEO, WATER, COLLAPS, THROW, BURN, DOME, TURN, ROPE_ANCHOR, ROPE_PULL, ROPE_UI, END };enum class OBJECTTYPE { DEFAULT, SONORA, INTERACTION, SPAWNOR, DESTRUCTION, NONRIGID, TRIGGERBOX, NONSONORA, NONSONORA_FLOOR, METEO, WATER, COLLAPS, THROW, BURN, DOME, TURN, ROPE_ANCHOR, ROPE_PULL, ROPE_UI, END };
	enum class OBJECTTYPE { DEFAULT, PARKOUR, GRAPPLE, END };
	enum class PARKOUR_FLAG {
		VAULTABLE	= 1 << 0, // 1
		CLIMBABLE	= 1 << 1, // 2
		HANGABLE	= 1 << 2, // 4
		MANTLEABLE	= 1 << 3, // 8
		ALL = 0xF, // 15
		END
	};

	// 이번 프레임에 실행 가능한 실제 파쿠르 액션.
	// HIGH_VAULT: 가슴 높이(무릎+가슴 히트)의 얇은 장애물을 한 번에 넘는 동작
	enum class PARKOUR_ACTION {
		NONE, LOW_VAULT, HIGH_VAULT, MANTLE, CLIMB, HANG, END
	};


	enum class MOVEMENT_TYPE {
		GROUND,
		CLIMB,
		END
	};


	enum class INSTANCETYPE { DEFAULT, SONORO, NONSONORO, END };

	enum class SHADER_VTXANIMMESH_PATH { DEFAULT, NORMAL, END};

	enum class ACTORDIR { U, RU, R, RD, D, LD, L, LU, END };

	enum class SONORA { NONE, SONORA, END };

	/* 
	* VAULT : 넘을 수 있는지
	* CLIMBABLE : 벽을 탈 수 있는지 (높아서?)
	* MANTLEABLE : 벽을 매달릴 수 있는지?
	*/
}