#pragma once

namespace Client
{
	enum class LEVEL { STATIC, LOGO, GAMEPLAY, HEAVEN, LOADING, TEST, TEST_UI, END };
	enum class COLLISIONLAYER { NONE, MAP, PLAYER, INTERACTION, GRAB, DETECT, SLIDE, BURN, THROW,GRAPPLE, INTERACT_THROW, END };
	enum class OBJECTTYPE { DEFAULT, INTERACTION, TRIGGERBOX, TURN, NONSONORA_FLOOR, NONRIGID, THROW, NONSONORA, SONORA, WATER, BURN, DOME, END };
	enum class INSTANCETYPE { DEFAULT, SONORO, NONSONORO, END };

	enum class SHADER_VTXANIMMESH_PATH { DEFAULT, NORMAL, END};

	enum class ACTORDIR { U, RU, R, RD, D, LD, L, LU, END };

	enum class SONORA { NONE, SONORA, END };
}